import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      app: { name: "SecureMoney", tagline: "Secure Digital Wallet" },
      nav: { dashboard: "Dashboard", send: "Send Money", receive: "Receive Money", withdraw: "Withdraw", deposit: "Deposit", airtime: "Airtime", bills: "Bill Payments", merchant: "Merchant Payments", history: "History", security: "Security", admin: "Admin", profile: "Profile", settings: "Settings", notifications: "Notifications", logout: "Logout" },
      auth: { login: "Sign In", register: "Create Account", email: "Email address", password: "Password", confirm_password: "Confirm Password", full_name: "Full Name", phone: "Phone Number", mfa_token: "Authentication Code", no_account: "Don't have an account?", have_account: "Already have an account?", sign_up: "Sign Up", forgot: "Forgot password?", or: "or continue with", welcome_back: "Welcome back", create_account: "Create your account", enter_details: "Enter your credentials to access your account", fill_details: "Fill in your details to get started", verify_email: "Verify Your Email", otp_token: "Verification Code", otp_sent: "A code has been sent to {email}", otp_sent_register: "OTP sent to your email!", resend_otp: "Resend code", verify: "Verify", passwords_mismatch: "Passwords do not match", password_min: "Password must be at least 8 characters", otp_send_failed: "Failed to send OTP", otp_resent: "OTP resent!", register_success: "Account created successfully!", verification_failed: "Verification failed", login_failed: "Login failed" },
      dashboard: { welcome: "Welcome", balance: "Total Balance", wallets: "Your Wallets", recent: "Recent Transactions", send: "Send Money", receive: "Receive", send_btn: "Send", receive_btn: "Receive", deposit_btn: "Deposit", withdraw_btn: "Withdraw", view_all: "View All", no_tx: "No recent transactions", quick_actions: "Quick Actions", monthly_spending: "Monthly Spending", overview: "Account Overview" },
      transfer: { title: "Send Money", from: "From Wallet", to: "Recipient Email", amount: "Amount", description: "Description (optional)", submit: "Send Money", success: "Transfer completed successfully!", failed: "Transfer failed. Please try again.", processing: "Processing transfer...", insufficient: "Insufficient funds", confirm: "Confirm Transfer", new_balance: "New Balance", fee: "Transfer Fee", recipient_label: "To" },
      receive: { title: "Receive Money", address: "Your Wallet Address", share: "Share your wallet address or QR code to receive payments", scan: "Scan to Pay", copy: "Copy Address", copied: "Address copied!", generate: "Generate QR Code" },
      history: { title: "Transaction History", no_tx: "No transactions yet", amount: "Amount", type: "Type", status: "Status", date: "Date", from: "From", to: "To", search: "Search transactions...", filter: "Filter", all: "All", completed: "Completed", pending: "Pending", failed: "Failed", export: "Export", receipt: "Receipt", download: "Download" },
      security: { title: "Security Settings", mfa: "Two-Factor Authentication", mfa_desc: "Add an extra layer of security to your account", enable: "Enable MFA", disable: "Disable MFA", scan_qr: "Scan this QR code with your authenticator app", enter_code: "Enter the 6-digit code from your authenticator app", verify: "Verify & Enable", success: "MFA has been enabled successfully", otp: "OTP Verification", pin: "Security PIN", pin_desc: "Set a security PIN for transactions", sessions: "Active Sessions", sessions_desc: "Manage your active login sessions", activity: "Login Activity", activity_desc: "View your recent login activity" },
      settings: { title: "Settings", language: "Language", theme: "Theme", light: "Light", dark: "Dark", system: "System", profile: "Profile Settings", profile_desc: "Manage your personal information", notifications: "Notification Preferences", currency: "Default Currency", save: "Save Changes" },
      profile: { title: "My Profile", personal: "Personal Information", email: "Email", phone: "Phone", full_name: "Full Name", member_since: "Member since", edit: "Edit Profile", update_success: "Profile updated successfully" },
      notifications: { title: "Notifications", mark_read: "Mark All as Read", no_notifications: "No notifications yet", transfer: "Transfer", security: "Security", info: "Information" },
      common: { loading: "Loading...", error: "Something went wrong", save: "Save", cancel: "Cancel", search: "Search", no_data: "No data available", confirm: "Confirm", delete: "Delete", edit: "Edit", close: "Close", back: "Back", next: "Next", done: "Done", copied: "Copied!", currency_tzs: "TZS", currency_usd: "USD", enabled: "Enabled", disabled: "Disabled" },
      landing: {
        nav: { features: "Features", how_it_works: "How It Works", testimonials: "Testimonials", faq: "FAQ", sign_in: "Sign In", get_started: "Get Started" },
        hero: { badge: "Trusted by 10,000+ users in Tanzania", title1: "Money Made", title2: "Simple", title3: "Send. Save. Invest.", subtitle: "The all-in-one finance app. Send money instantly, get a debit card, invest in stocks and Bitcoin, earn cashback, and reach your savings goals.", cta: "Get Started Free", signin_btn: "Sign In", security: "Bank-Grade Security", instant: "Instant Transfers", cashback: "Cashback Rewards", mock_balance: "Total Balance", mock_investments: "Investments", mock_bitcoin: "Bitcoin", mock_send: "Send Money", mock_card: "Cash Card" },
        stats: { users: "Active Users", transactions: "Transactions Daily", uptime: "Uptime", rating: "App Store Rating" },
        how: { title: "How It Works", subtitle: "Get started in minutes. No branches, no paperwork, no hassle.", step1_title: "Download & Sign Up", step1_desc: "Create your free account in under 2 minutes. No paperwork, no branches.", step2_title: "Add Funds", step2_desc: "Deposit money via bank transfer, card, or mobile money. Start with any amount.", step3_title: "Start Transacting", step3_desc: "Send money, pay bills, invest, or shop. Everything at your fingertips." },
        features: { title: "Everything You Need", subtitle: "One app for sending, spending, saving, and investing. SecureMoney puts you in control.", f1_title: "Instant Transfers", f1_desc: "Send money instantly to any SecureMoney user. No fees for person-to-person payments, no waiting.", f2_title: "SecureMoney Card", f2_desc: "Get a virtual or physical debit card linked to your wallet. Use it anywhere, online or in-store.", f3_title: "Invest in Stocks", f3_desc: "Start investing with as little as $1. Buy fractional shares of top companies and grow your wealth.", f4_title: "Bitcoin & Crypto", f4_desc: "Buy, sell, and hold Bitcoin and other cryptocurrencies directly from your wallet.", f5_title: "Savings Goals", f5_desc: "Set savings goals and automate deposits. Watch your money grow with competitive interest rates.", f6_title: "Cashback Rewards", f6_desc: "Earn instant cashback when you pay at participating merchants. Boost your savings automatically.", f7_title: "Mobile First", f7_desc: "Manage your money anytime, anywhere. Pay bills, buy airtime, and control your finances from your phone.", f8_title: "Multi-Currency", f8_desc: "Hold and transact in TZS, USD, and more. Convert between currencies at competitive rates instantly.", f9_title: "QR Payments", f9_desc: "Pay at any store by scanning a QR code. No cards, no cash, no hassle." },
        card: { title: "The SecureMoney Card", subtitle: "A debit card that works everywhere. Order a free virtual card instantly, or get a physical card delivered to your door.", item1: "Free virtual card available instantly", item2: "Physical card delivered free of charge", item3: "Works anywhere debit cards are accepted", item4: "Real-time spending notifications", item5: "Freeze and unfreeze from the app", item6: "ATM withdrawals with no fees", cta: "Get Your Card" },
        invest: { title: "Invest & Grow", subtitle: "Start investing with as little as $1. Buy fractional shares of top companies, trade Bitcoin, and watch your money grow.", item1: "Buy fractional shares of Apple, Tesla, Google and more", item2: "Invest in Bitcoin and other cryptocurrencies", item3: "Start with as little as $1 - no minimum balance", item4: "Real-time market data and portfolio tracking", item5: "Set up recurring investments automatically", stat1: "Portfolio Return", stat2: "Bitcoin Price" },
        cashback: { title: "Earn Cashback Every Day", subtitle: "Get instant cashback when you pay at hundreds of participating merchants. Your rewards are added to your wallet automatically.", item1: "Up to 10% cashback at partner merchants", item2: "Rewards added instantly to your wallet", item3: "New boosts added every week", item4: "Stack rewards on top of sales and discounts", item5: "No minimum spend to earn cashback", cta: "Start Earning", boosts_title: "Active Boosts", boost1: "Supermarket Co.", boost2: "Fuel Station", boost3: "Coffee Shop", boost4: "Online Store" },
        security: { title: "Bank-Grade Security", subtitle: "Your security is our foundation. Every transaction, every piece of data — protected by the strongest encryption available.", item1: "AES-256-GCM encryption for all sensitive data", item2: "Argon2 password hashing — the gold standard", item3: "Two-factor authentication (2FA) support", item4: "Real-time fraud monitoring and alerts", item5: "Regular security audits and penetration testing", item6: "FDIC insured up to $250,000", card_title: "Your Data is Safe", card_desc: "Protected by military-grade encryption and industry best practices." },
        referral: { title: "Refer & Earn", subtitle: "Share SecureMoney with friends and earn TZS 5,000 for every friend who signs up and makes their first transaction.", step1_title: "Share your link", step1_desc: "Send your unique referral code", step2_title: "They sign up", step2_desc: "Friend creates a free account", step3_title: "You both earn", step3_desc: "TZS 5,000 credited to your wallet", cta: "Start Referring" },
        testimonials: { title: "Loved by Thousands", subtitle: "Join the growing community of SecureMoney users who trust us with their finances.", t1_name: "Sarah J.", t1_role: "Small Business Owner", t1_text: "SecureMoney transformed how I manage my business finances. The Cash Card and instant transfers are game changers.", t2_name: "David M.", t2_role: "Freelancer", t2_text: "The investing feature is incredible. I started with just $10 and now I'm growing my portfolio alongside my savings.", t3_name: "Grace K.", t3_role: "Student", t3_text: "Paying bills, buying airtime, and getting cashback — all in one app. I recommend SecureMoney to all my friends.", t4_name: "James W.", t4_role: "Teacher", t4_text: "The savings goals feature helped me save for my daughter's school fees. The interest rates are the best I've found." },
        faq: { title: "Got Questions?", subtitle: "Everything you need to know about SecureMoney.", q1: "How do I create an account?", a1: "Simply sign up on our website or download the app. You'll need a valid email address and a strong password. Registration takes less than 2 minutes and is completely free.", q2: "Is my money safe with SecureMoney?", a2: "Absolutely. We use AES-256-GCM encryption for all sensitive data, Argon2 for password hashing, and offer two-factor authentication. Your security is our top priority.", q3: "How does the SecureMoney Card work?", a3: "Once you have funds in your wallet, you can order a virtual or physical debit card. It works anywhere debit cards are accepted, online and in stores.", q4: "Can I invest in stocks and Bitcoin?", a4: "Yes! You can start investing in stocks with as little as $1. We offer fractional shares of major companies. You can also buy, sell, and hold Bitcoin and other cryptocurrencies.", q5: "What is Cashback Rewards?", a5: "When you pay at participating merchants, you earn a percentage of your purchase back as cash. Rewards are automatically added to your wallet instantly.", q6: "Are there any fees?", a6: "Person-to-person transfers are free. Small fees apply for bill payments, airtime purchases, and currency conversions. Investing fees are competitive and transparent." },
        cta: { title: "Ready to Get Started?", subtitle: "Join thousands of users who trust SecureMoney for sending, spending, saving, and investing.", button: "Create Free Account", badge1: "Encrypted & Secure", badge2: "Instant Setup", badge3: "Free to Join" },
        footer: { desc: "The all-in-one finance app. Send, spend, save, and invest — all from your phone.", product_title: "Product", company_title: "Company", contact_title: "Contact", product1: "Send Money", product2: "Cash Card", product3: "Investing", product4: "Bitcoin", product5: "Cashback Rewards", company1: "About Us", company2: "Blog", company3: "Careers", company4: "Press", company5: "Contact", address: "Dar es Salaam, Tanzania", copyright: "All rights reserved. Created by Coderoom." }
      },
      admin: {
        dashboard: "Admin Dashboard", users: "Users", audit: "Audit Logs", roles: "Roles", analytics: "Analytics", total_users: "Total Users", total_tx: "Total Transactions", total_wallets: "Total Wallets", recent_users: "Recent Users", create_role: "Create Role", role_name: "Role Name", actions: "Actions", no_logs: "No audit logs found", filter_action: "Filter by action",
        overview: "Overview of the SecureMoney platform",
        agents: "Agent Management", agents_desc: "Manage platform agents", search_agents: "Search agents...", new_agent: "New Agent", create_agent: "Create Agent", agent_name: "Name", agent_email: "Email", agent_phone: "Phone", agent_created: "Created", no_agents: "No agents found", creating: "Creating...",
        merchants: "Merchant Management", merchants_desc: "Manage platform merchants", search_merchants: "Search merchants...", new_merchant: "New Merchant", create_merchant: "Create Merchant", merchant_name: "Business Name", merchant_email: "Email", merchant_phone: "Phone", merchant_created: "Created", no_merchants: "No merchants found",
        reports: "Reports", reports_desc: "Platform analytics and statistics", refresh: "Refresh", total_deposits: "Deposits", total_withdrawals: "Withdrawals", total_transfers: "Transfers", completed: "Completed", failed: "Failed", activity_30d: "30-Day Activity", tx_distribution: "Transaction Distribution", success_rate: "Success Rate", success: "Success",
        settings: "System Settings", settings_desc: "Configure platform-wide settings", general: "General", security_section: "Security", financial: "Financial", session: "Session", site_name: "Site Name", support_email: "Support Email", maintenance: "Maintenance Mode", maintenance_desc: "Block all user access except admins", registration: "Registration Open", registration_desc: "Allow new users to register", mfa_required: "Require MFA", mfa_required_desc: "Force all users to enable 2FA", default_currency: "Default Currency", min_withdrawal: "Min Withdrawal", max_withdrawal: "Max Withdrawal", session_timeout: "Session Timeout (minutes)", save_settings: "Save Settings", saving: "Saving...",
        content: "Content Management", content_desc: "Edit website content and copy", refresh_content: "Refresh", no_content: "No Content Pages", no_content_desc: "Content management data is not available yet.",
        wallets: "Wallet Overview", wallets_desc: "View all wallets across the platform", wallet_id: "Wallet ID", balance: "Balance", currency: "Currency", active: "Active", inactive: "Inactive", no_wallets: "No wallets found",
        transactions: "Transaction Management", all_types: "All Types", all_status: "All Status", type: "Type", amount: "Amount", status: "Status", date: "Date", no_tx: "No transactions found",
        deposits: "Deposit Management", deposits_desc: "Monitor and manage all deposit transactions", no_deposits: "No deposits found",
        withdrawals: "Withdrawal Management", withdrawals_desc: "Monitor and manage all withdrawal transactions", no_withdrawals: "No withdrawals found",
        security_page: "Security Audit Log", security_desc: "Monitor all security events and administrative actions", filter_action_placeholder: "Filter by action...", no_logs_found: "No audit logs found",
        notifications: "Broadcast Notification", notifications_desc: "Send a notification to all platform users", title: "Title", message: "Message", send: "Broadcast Notification", sending: "Sending...",
        users_title: "User Management", search_users: "Search users...", no_users: "No users found", email: "Email", role: "Role", mfa: "MFA", joined: "Joined",
        sidebar: { dashboard: "Dashboard", users: "Users", transactions: "Transactions", deposits: "Deposits", withdrawals: "Withdrawals", wallets: "Wallets", agents: "Agents", merchants: "Merchants", reports: "Reports", security: "Security", settings: "Settings", notifications: "Notifications", content: "Content" }
      }
    }
  },
  sw: {
    translation: {
      app: { name: "SecureMoney", tagline: "Mkoba Salama Dijitali" },
      nav: { dashboard: "Dashibodi", send: "Tuma Pesa", receive: "Pokea Pesa", withdraw: "Toa Pesa", deposit: "Weka Pesa", airtime: "Airtime", bills: "Malipo ya Bili", merchant: "Malipo ya Biashara", history: "Historia", security: "Usalama", admin: "Wasimamizi", profile: "Wasifu", settings: "Mipangilio", notifications: "Arifa", logout: "Toka" },
      auth: { login: "Ingia", register: "Fungua Akaunti", email: "Barua pepe", password: "Nywila", confirm_password: "Thibitisha Nywila", full_name: "Jina Kamili", phone: "Nambari ya Simu", mfa_token: "Msimbo wa Uthibitishaji", no_account: "Huna akaunti?", have_account: "Tayari una akaunti?", sign_up: "Jisajili", forgot: "Umesahau nywila?", or: "au endelea na", welcome_back: "Karibu tena", create_account: "Fungua akaunti yako", enter_details: "Weka hati zako kufikia akaunti yako", fill_details: "Jaza maelezo yako kuanza", verify_email: "Thibitisha Barua Pepe", otp_token: "Msimbo wa Uthibitishaji", otp_sent: "Msimbo umetumwa kwa {email}", otp_sent_register: "OTP imetumwa kwa barua pepe yako!", resend_otp: "Tuma tena msimbo", verify: "Thibitisha", passwords_mismatch: "Nywila hazilingani", password_min: "Nywila lazima iwe na angalau herufi 8", otp_send_failed: "Imeshindwa kutuma OTP", otp_resent: "OTP imetumwa tena!", register_success: "Akaunti imeundwa kwa mafanikio!", verification_failed: "Uthibitishaji umeshindikana", login_failed: "Kuingia kumekataliwa" },
      dashboard: { welcome: "Karibu", balance: "Jumla ya Salio", wallets: "Mikoba Yako", recent: "Shughuli za Hivi Karibuni", send: "Tuma Pesa", receive: "Pokea", send_btn: "Tuma", receive_btn: "Pokea", deposit_btn: "Weka", withdraw_btn: "Toa", view_all: "Angalia Zote", no_tx: "Hakuna shughuli za hivi karibuni", quick_actions: "Vitendo vya Haraka", monthly_spending: "Matumizi ya Mwezi", overview: "Muhtasari wa Akaunti" },
      transfer: { title: "Tuma Pesa", from: "Kutoka kwenye Mkoba", to: "Barua pepe ya Mpokeaji", amount: "Kiasi", description: "Maelezo (si lazima)", submit: "Tuma Pesa", success: "Uhamisho umekamilika!", failed: "Uhamisho umeshindikana. Tafadhali jaribu tena.", processing: "Inashughulikia uhamisho...", insufficient: "Salio haitoshi", confirm: "Thibitisha Uhamisho", new_balance: "Salio Jipya", fee: "Ada ya Uhamisho", recipient_label: "Kwa" },
      receive: { title: "Pokea Pesa", address: "Anwani ya Mkoba Wako", share: "Shiriki anwani yako ya mkoba au msimbo wa QR kupokea malipo", scan: "Changanua Kulipa", copy: "Nakili Anwani", copied: "Anwani imenakiliwa!", generate: "Tengeneza Msimbo wa QR" },
      history: { title: "Historia ya Uhamisho", no_tx: "Hakuna uhamisho bado", amount: "Kiasi", type: "Aina", status: "Hali", date: "Tarehe", from: "Kutoka", to: "Kwa", search: "Tafuta uhamisho...", filter: "Chuja", all: "Zote", completed: "Imekamilika", pending: "Inasubiri", failed: "Imeshindikana", export: "Hamisha", receipt: "Risiti", download: "Pakua" },
      security: { title: "Mipangilio ya Usalama", mfa: "Uthibitishaji wa Hatua Mbili", mfa_desc: "Ongeza safu ya ziada ya usalama kwa akaunti yako", enable: "Washa MFA", disable: "Zima MFA", scan_qr: "Changanua msimbo huu wa QR kwa programu yako ya uthibitishaji", enter_code: "Ingiza msimbo wa tarakimu 6 kutoka kwa programu yako", verify: "Thibitisha na Washa", success: "MFA imewashwa kwa mafanikio", otp: "Uthibitishaji wa OTP", pin: "Nambari ya PIN ya Usalama", pin_desc: "Weka nambari ya PIN kwa ajili ya shughuli", sessions: "Vipindi Amilifu", sessions_desc: "Simamia vipindi vyako vya kuingia", activity: "Shughuli za Kuingia", activity_desc: "Angalia shughuli zako za hivi karibuni za kuingia" },
      settings: { title: "Mipangilio", language: "Lugha", theme: "Mandhari", light: "Mwangaza", dark: "Giza", system: "Mfumo", profile: "Mipangilio ya Wasifu", profile_desc: "Simamia taarifa zako binafsi", notifications: "Mapendeleo ya Arifa", currency: "Sarafu Chaguo-msingi", save: "Hifadhi Mabadiliko" },
      profile: { title: "Wasifu Wangu", personal: "Taarifa Binafsi", email: "Barua pepe", phone: "Simu", full_name: "Jina Kamili", member_since: "Mwanachama tangu", edit: "Hariri Wasifu", update_success: "Wasifu umesasishwa kwa mafanikio" },
      notifications: { title: "Arifa", mark_read: "Weka Zote Kama Zimesomwa", no_notifications: "Hakuna arifa bado", transfer: "Uhamisho", security: "Usalama", info: "Taarifa" },
      common: { loading: "Inapakia...", error: "Kuna hitilafu imetokea", save: "Hifadhi", cancel: "Ghairi", search: "Tafuta", no_data: "Hakuna data", confirm: "Thibitisha", delete: "Futa", edit: "Hariri", close: "Funga", back: "Nyuma", next: "Endelea", done: "Imekamilika", copied: "Imenakiliwa!", currency_tzs: "TZS", currency_usd: "USD", enabled: "Imewashwa", disabled: "Imezimwa" },
      landing: {
        nav: { features: "Vipengele", how_it_works: "Inavyofanya Kazi", testimonials: "Maoni", faq: "Maswali", sign_in: "Ingia", get_started: "Anza" },
        hero: { badge: "Inatumiwa na watumiaji 10,000+ Tanzania", title1: "Pesa Yako", title2: "Rahisi", title3: "Tuma. Weka. Wekeza.", subtitle: "Programu ya fedha ya kufanya yote. Tuma pesa papo hapo, pata kadi ya benki, wekeza katika hisa na Bitcoin, pata cashback, na fikia malengo yako ya akiba.", cta: "Anza Bure", signin_btn: "Ingia", security: "Usalama wa Benki", instant: "Uhamisho Papo hapo", cashback: "Zawadi za Cashback", mock_balance: "Jumla ya Salio", mock_investments: "Uwekezaji", mock_bitcoin: "Bitcoin", mock_send: "Tuma Pesa", mock_card: "Kadi ya Pesa" },
        stats: { users: "Watumiaji Hai", transactions: "Shughuli Kila Siku", uptime: "Muda wa Kazi", rating: "Ukadiriaji wa Duka" },
        how: { title: "Inavyofanya Kazi", subtitle: "Anza kwa dakika chache. Hakuna matawi, hakuna makaratasi, hakuna taabu.", step1_title: "Pakua na Jisajili", step1_desc: "Unda akaunti yako bure kwa chini ya dakika 2. Hakuna makaratasi, hakuna matawi.", step2_title: "Weka Pesa", step2_desc: "Weka pesa kwa njia ya benki, kadi, au pesa za mkononi. Anza na kiasi chochote.", step3_title: "Anza Shughuli", step3_desc: "Tuma pesa, lipa bili, wekeza, au nunua. Kila kitu mkononi mwako." },
        features: { title: "Kila Kitu Unachohitaji", subtitle: "Programu moja kwa ajili ya kutuma, kutumia, kuweka, na kuwekeza. SecureMoney inakuweka wewe katika udhibiti.", f1_title: "Uhamisho Papo Hapo", f1_desc: "Tuma pesa papo hapo kwa mtumiaji yeyote wa SecureMoney. Hakuna ada kwa malipo ya mtu kwa mtu.", f2_title: "Kadi ya SecureMoney", f2_desc: "Pata kadi ya benki pepe au halisi iliyounganishwa na mkoba wako. Itumie popote, mtandaoni au dukani.", f3_title: "Wekeza kwenye Hisa", f3_desc: "Anza kuwekeza kwa chini ya $1. Nunua hisa za sehemu za makampuni makubwa na kukuza utajiri wako.", f4_title: "Bitcoin na Crypto", f4_desc: "Nunua, uze, na shikilia Bitcoin na sarafu nyingine za dijitali moja kwa moja kutoka kwenye mkoba wako.", f5_title: "Malengo ya Akiba", f5_desc: "Weka malengo ya akiba na kiotomatiki amana. Tazama pesa zako zikiongezeka kwa viwango vya riba vinavyoshindana.", f6_title: "Zawadi za Cashback", f6_desc: "Pata cashback papo hapo unapolipa kwa wafanyabiashara wanaoshiriki. Ongeza akiba yako kiotomatiki.", f7_title: "Simu Kwanza", f7_desc: "Simamia pesa zako wakati wowote, mahali popote. Lipa bili, nunua airtime, na udhibiti fedha zako kwenye simu yako.", f8_title: "Sarafu Nyingi", f8_desc: "Shikilia na fanya shughuli kwa TZS, USD, na zaidi. Badilisha sarafu kwa viwango vya ushindani papo hapo.", f9_title: "Malipo ya QR", f9_desc: "Lipa dukani kwa kuchanganua msimbo wa QR. Hakuna kadi, hakuna pesa taslimu, hakuna taabu." },
        card: { title: "Kadi ya SecureMoney", subtitle: "Kadi ya benki inayofanya kazi kila mahali. Agiza kadi pepe bure papo hapo, au pata kadi halisi ikifika mlangoni.", item1: "Kadi pepe bure inapatikana papo hapo", item2: "Kadi halisi inatumwa bure", item3: "Inafanya kazi popote kadi za benki zinakubaliwa", item4: "Arifa za matumizi kwa wakati halisi", item5: "Gandisha na fungua kutoka kwenye programu", item6: "Utoaji wa ATM bila ada", cta: "Pata Kadi Yako" },
        invest: { title: "Wekeza na Kua", subtitle: "Anza kuwekeza kwa chini ya $1. Nunua hisa za sehemu za makampuni makubwa, fanya biashara ya Bitcoin, na tazama pesa zako zikiongezeka.", item1: "Nunua hisa za sehemu za Apple, Tesla, Google na zaidi", item2: "Wekeza kwenye Bitcoin na sarafu nyingine za dijitali", item3: "Anza kwa chini ya $1 - hakuna kiwango cha chini", item4: "Data ya soko la wakati halisi na ufuatiliaji wa kwingineko", item5: "Weka uwekezaji unaojirudia kiotomatiki", stat1: "Mapato ya Kwingineko", stat2: "Bei ya Bitcoin" },
        cashback: { title: "Pata Cashback Kila Siku", subtitle: "Pata cashback papo hapo unapolipa kwa mamia ya wafanyabiashara wanaoshiriki. Zawadi zako zinaongezwa kwenye mkoba wako kiotomatiki.", item1: "Hadi 10% cashback kwa wafanyabiashara washirika", item2: "Zawadi zinaongezwa papo hapo kwenye mkoba wako", item3: "Nyongeza mpya kila wiki", item4: "Rundika zawadi juu ya mauzo na punguzo", item5: "Hakuna kiwango cha chini cha matumizi kupata cashback", cta: "Anza Kupata", boosts_title: "Nyongeza Amilifu", boost1: "Supermarket Co.", boost2: "Kituo cha Mafuta", boost3: "Kahawa", boost4: "Duka la Mtandaoni" },
        security: { title: "Usalama wa Benki", subtitle: "Usalama wako ndio msingi wetu. Kila shughuli, kila kipande cha data — kinalindwa na usimbaji fiche wenye nguvu zaidi.", item1: "Usimbaji fiche AES-256-GCM kwa data zote nyeti", item2: "Ufungashaji wa nywila wa Argon2 — kiwango cha dhahabu", item3: "Uthibitishaji wa hatua mbili (2FA)", item4: "Ufuatiliaji wa ulaghai wa wakati halisi na arifa", item5: "Ukaguzi wa usalama wa mara kwa mara na majaribio ya kupenya", item6: "Bima ya FDIC hadi $250,000", card_title: "Data Yako ni Salama", card_desc: "Inalindwa na usimbaji fiche wa kiwango cha kijeshi na mbinu bora za sekta." },
        referral: { title: "Rejelea na Pata", subtitle: "Shiriki SecureMoney na marafiki na upate TZS 5,000 kwa kila rafiki anayejisajili na kufanya shughuli yake ya kwanza.", step1_title: "Shiriki kiungo chako", step1_desc: "Tuma msimbo wako wa kipekee wa urejelezaji", step2_title: "Wanajisajili", step2_desc: "Rafiki anafungua akaunti bure", step3_title: "Nyote mnapata", step3_desc: "TZS 5,000 zinawekwa kwenye mkoba wako", cta: "Anza Kurejelea" },
        testimonials: { title: "Kupendwa na Maelfu", subtitle: "Jiunge na jamii inayokua ya watumiaji wa SecureMoney wanaoamini kwa fedha zao.", t1_name: "Sarah J.", t1_role: "Mfanyabiashara Mdogo", t1_text: "SecureMoney imebadilisha jinsi ninavyosimamia fedha za biashara yangu. Kadi ya Cash na uhamisho papo hapo ni mabadiliko makubwa.", t2_name: "David M.", t2_role: "Mfanyakazi Huru", t2_text: "Kipengele cha uwekezaji ni cha ajabu. Nilianza kwa $10 tu na sasa ninakua kwingineko yangu pamoja na akiba yangu.", t3_name: "Grace K.", t3_role: "Mwanafunzi", t3_text: "Kulipa bili, kununua airtime, na kupata cashback — zote kwenye programu moja. Ninapendekeza SecureMoney kwa marafiki zangu wote.", t4_name: "James W.", t4_role: "Mwalimu", t4_text: "Kipengele cha malengo ya akiba kilinisaidia kuweka akiba kwa ada za shule za binti yangu. Viwango vya riba ndio bora zaidi nimevipata." },
        faq: { title: "Una Maswali?", subtitle: "Kila kitu unachohitaji kujua kuhusu SecureMoney.", q1: "Ninaundaje akaunti?", a1: "Jisajili kwenye tovuti yetu au pakua programu. Utahitaji barua pepe halali na nywila imara. Usajili unachukua chini ya dakika 2 na ni bure kabisa.", q2: "Je, pesa zangu ziko salama kwa SecureMoney?", a2: "Kabisa. Tunatumia usimbaji fiche AES-256-GCM kwa data zote nyeti, Argon2 kwa ufungashaji wa nywila, na tunatoa uthibitishaji wa hatua mbili. Usalama wako ni kipaumbele chetu.", q3: "Kadi ya SecureMoney inafanya kazi vipi?", a3: "Mara baada ya kuwa na fedha kwenye mkoba wako, unaweza kuagiza kadi pepe au halisi. Inafanya kazi popote kadi za benki zinakubaliwa, mtandaoni na dukani.", q4: "Naweza kuwekeza kwenye hisa na Bitcoin?", a4: "Ndiyo! Unaweza kuanza kuwekeza kwenye hisa kwa chini ya $1. Tunatoa hisa za sehemu za makampuni makubwa. Unaweza pia kununua, kuuza, na kushikilia Bitcoin na sarafu nyingine za dijitali.", q5: "Cashback Rewards ni nini?", a5: "Unapolipa kwa wafanyabiashara wanaoshiriki, unapata asilimia ya ununuzi wako kama pesa taslimu. Zawadi zinaongezwa kwenye mkoba wako kiotomatiki papo hapo.", q6: "Kuna ada zozote?", a6: "Uhamisho wa mtu kwa mtu ni bure. Ada ndogo zinatumika kwa malipo ya bili, ununuzi wa airtime, na ubadilishaji wa sarafu. Ada za uwekezaji ni za ushindani na wazi." },
        cta: { title: "Uko Taya Kuanza?", subtitle: "Jiunge na maelfu ya watumiaji wanaoamini SecureMoney kwa kutuma, kutumia, kuweka, na kuwekeza.", button: "Fungua Akaunti Bure", badge1: "Imesimbwa na Salama", badge2: "Kuanzishwa Papo Hapo", badge3: "Bure Kujiunga" },
        footer: { desc: "Programu ya fedha ya kufanya yote. Tuma, tumia, weka, na wekeza — zote kutoka kwenye simu yako.", product_title: "Bidhaa", company_title: "Kampuni", contact_title: "Wasiliana", product1: "Tuma Pesa", product2: "Kadi ya Pesa", product3: "Uwekezaji", product4: "Bitcoin", product5: "Zawadi za Cashback", company1: "Kuhusu Sisi", company2: "Blogu", company3: "Ajira", company4: "Vyombo vya Habari", company5: "Wasiliana", address: "Dar es Salaam, Tanzania", copyright: "Haki zote zimehifadhiwa. Imeundwa na Coderoom." }
      },
      admin: {
        dashboard: "Dashibodi ya Wasimamizi", users: "Watumiaji", audit: "Kumbukumbu", roles: "Majukumu", analytics: "Takwimu", total_users: "Jumla ya Watumiaji", total_tx: "Jumla ya Uhamisho", total_wallets: "Jumla ya Mikoba", recent_users: "Watumiaji wa Hivi Karibuni", create_role: "Unda Jukumu", role_name: "Jina la Jukumu", actions: "Vitendo", no_logs: "Hakuna kumbukumbu za ukaguzi", filter_action: "Chuja kwa hatua",
        overview: "Muhtasari wa mfumo wa SecureMoney",
        agents: "Usimamizi wa Mawakala", agents_desc: "Simamia mawakala wa mfumo", search_agents: "Tafuta mawakala...", new_agent: "Mwakala Mpya", create_agent: "Unda Mwakala", agent_name: "Jina", agent_email: "Barua pepe", agent_phone: "Simu", agent_created: "Imeundwa", no_agents: "Hakuna mawakala waliopatikana", creating: "Inaunda...",
        merchants: "Usimamizi wa Wafanyabiashara", merchants_desc: "Simamia wafanyabiashara wa mfumo", search_merchants: "Tafuta wafanyabiashara...", new_merchant: "Mfanyabiashara Mpya", create_merchant: "Unda Mfanyabiashara", merchant_name: "Jina la Biashara", merchant_email: "Barua pepe", merchant_phone: "Simu", merchant_created: "Imeundwa", no_merchants: "Hakuna wafanyabiashara waliopatikana",
        reports: "Ripoti", reports_desc: "Takwimu na uchambuzi wa mfumo", refresh: "Onyesha upya", total_deposits: "Weka Pesa", total_withdrawals: "Toa Pesa", total_transfers: "Uhamisho", completed: "Imekamilika", failed: "Imeshindikana", activity_30d: "Shughuli za Siku 30", tx_distribution: "Usambazaji wa Shughuli", success_rate: "Kiwango cha Mafanikio", success: "Mafanikio",
        settings: "Mipangilio ya Mfumo", settings_desc: "Sanidi mipangilio ya mfumo mzima", general: "Mkuu", security_section: "Usalama", financial: "Kifedha", session: "Kipindi", site_name: "Jina la Tovuti", support_email: "Barua pepe ya Msaada", maintenance: "Hali ya Matengenezo", maintenance_desc: "Zuia ufikiaji wote wa watumiaji isipokuwa wasimamizi", registration: "Usajili Wazi", registration_desc: "Ruhusu watumiaji wapya kujisajili", mfa_required: "Hitaji MFA", mfa_required_desc: "Lazimisha watumiaji wote kuwezesha 2FA", default_currency: "Sarafu Chaguo-msingi", min_withdrawal: "Kiwango cha Chini cha Utoaji", max_withdrawal: "Kiwango cha Juu cha Utoaji", session_timeout: "Muda wa Kuisha kwa Kipindi (dakika)", save_settings: "Hifadhi Mipangilio", saving: "Inahifadhi...",
        content: "Usimamizi wa Maudhui", content_desc: "Hariri maudhui na nakala za tovuti", refresh_content: "Onyesha upya", no_content: "Hakuna Kurasa za Maudhui", no_content_desc: "Data ya usimamizi wa maudhui haipatikani bado.",
        wallets: "Muhtasari wa Mikoba", wallets_desc: "Angalia mikoba yote kwenye mfumo", wallet_id: "Kitambulisho cha Mkoba", balance: "Salio", currency: "Sarafu", active: "Inatumika", inactive: "Haitumiki", no_wallets: "Hakuna mikoba iliyopatikana",
        transactions: "Usimamizi wa Shughuli", all_types: "Aina Zote", all_status: "Hali Zote", type: "Aina", amount: "Kiasi", status: "Hali", date: "Tarehe", no_tx: "Hakuna shughuli zilizopatikana",
        deposits: "Usimamizi wa Weka Pesa", deposits_desc: "Fuatilia na simamia shughuli zote za weka pesa", no_deposits: "Hakuna weka pesa zilizopatikana",
        withdrawals: "Usimamizi wa Toa Pesa", withdrawals_desc: "Fuatilia na simamia shughuli zote za toa pesa", no_withdrawals: "Hakuna toa pesa zilizopatikana",
        security_page: "Kumbukumbu za Usalama", security_desc: "Fuatilia matukio yote ya usalama na hatua za kiutawala", filter_action_placeholder: "Chuja kwa hatua...", no_logs_found: "Hakuna kumbukumbu za ukaguzi zilizopatikana",
        notifications: "Arifa za Matangazo", notifications_desc: "Tuma arifa kwa watumiaji wote wa mfumo", title: "Kichwa", message: "Ujumbe", send: "Tuma Matangazo", sending: "Inatuma...",
        users_title: "Usimamizi wa Watumiaji", search_users: "Tafuta watumiaji...", no_users: "Hakuna watumiaji waliopatikana", email: "Barua pepe", role: "Jukumu", mfa: "MFA", joined: "Alijiunga",
        sidebar: { dashboard: "Dashibodi", users: "Watumiaji", transactions: "Shughuli", deposits: "Weka Pesa", withdrawals: "Toa Pesa", wallets: "Mikoba", agents: "Mawakala", merchants: "Wafanyabiashara", reports: "Ripoti", security: "Usalama", settings: "Mipangilio", notifications: "Arifa", content: "Maudhui" }
      }
    }
  }
};

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem("lang") || "en",
  fallbackLng: "en",
  interpolation: { escapeValue: false }
});

export default i18n;
